{
"asc":true,
"autoCount":${logPage.autoCount?string("true","false")},
"inverseOrder":"DESC",
"nextEnabled":false,
"order":"ASC",
"orderBy":"${logPage.getOrderBy()!""}",
"orderEnabled":false,
"pageCount":#{logPage.pageCount!-1},
"pageCountEnabled":false,
"pageNo":#{logPage.pageNo!1},
"pageSize":#{logPage.pageSize!0},
"pageSizeEnabled":false,
"previousEnabled":false,
"result":${logPage.result!""},
"start":#{logPage.start!0},
"startEnabled":true,
"totalCount":#{logPage.totalCount!-1}
}