{
"asc":true,
"autoCount":${errPage.autoCount?string("true","false")},
"inverseOrder":"DESC",
"nextEnabled":false,
"order":"ASC",
"orderBy":"${errPage.getOrderBy()!""}",
"orderEnabled":false,
"pageCount":#{errPage.pageCount!-1},
"pageCountEnabled":false,
"pageNo":#{errPage.pageNo!1},
"pageSize":#{errPage.pageSize!0},
"pageSizeEnabled":false,
"previousEnabled":false,
"result":${errPage.result!""},
"start":#{errPage.start!0},
"startEnabled":true,
"totalCount":#{errPage.totalCount!-1}
}