{
"asc":true,
"autoCount":${pageListPage.autoCount?string("true","false")},
"inverseOrder":"DESC",
"nextEnabled":false,
"order":"ASC",
"orderBy":"${pageListPage.getOrderBy()!""}",
"orderEnabled":false,
"pageCount":#{pageListPage.pageCount!-1},
"pageCountEnabled":false,
"pageNo":#{pageListPage.pageNo!1},
"pageSize":#{pageListPage.pageSize!0},
"pageSizeEnabled":false,
"previousEnabled":false,
"result":${pageListPage.result!""},
"start":#{pageListPage.start!0},
"startEnabled":true,
"totalCount":#{pageListPage.totalCount!-1}
}